### ISSUE TITLE
make[2]: *** [install-nobase_follyincludeHEADERS] Error 1

### ISSUE THREAD

**Issue by mszlazak** [facebook/fbcunn#65]
Got this at the end of installing Folly, etc:

 /bin/mkdir -p '/usr/local/include/folly/experimental/fibers'
 /usr/bin/install -c -m 644  experimental/fibers/AddTasks.h experimental/fibers/AddTasks-inl.h experimental/fibers/Baton.h experimental/fibers/Baton-inl.h experimental/fibers/BoostContextCompatibility.h experimental/fibers/EventBaseLoopController.h experimental/fibers/EventBaseLoopController-inl.h experimental/fibers/Fiber.h experimental/fibers/Fiber-inl.h experimental/fibers/FiberManager.h experimental/fibers/FiberManager-inl.h experimental/fibers/FiberManagerMap.h experimental/fibers/ForEach.h experimental/fibers/ForEach-inl.h experimental/fibers/GenericBaton.h experimental/fibers/GuardPageAllocator.h experimental/fibers/LoopController.h experimental/fibers/Promise.h experimental/fibers/Promise-inl.h experimental/fibers/SimpleLoopController.h experimental/fibers/TimedMutex.h experimental/fibers/TimedMutex-inl.h experimental/fibers/TimeoutController.h experimental/fibers/TimeoutController.h experimental/fibers/traits.h experimental/fibers/WhenN.h experimental/fibers/WhenN-inl.h '/usr/local/include/folly/experimental/fibers'
/usr/bin/install: will not overwrite just-created ‘/usr/local/include/folly/experimental/fibers/TimeoutController.h’ with ‘experimental/fibers/TimeoutController.h’
make[2]: *** [install-nobase_follyincludeHEADERS] Error 1
make[2]: Leaving directory `/tmp/fblualib-build.Mm0XOa/folly/folly'
make[1]: *** [install-am] Error 2
make[1]: Leaving directory `/tmp/fblualib-build.Mm0XOa/folly/folly'
make: *** [install-recursive] Error 1

**Comment by soumith** [comment]
I am going to build binaries for this package later today and post a zip
file. The folly /thpp install is soo sooo finicky

**Comment by mszlazak** [comment]
Thank you! My buddy who has more experience than me tried to fix a bunch of stuff ... he did so well that i had to reinstall Ubuntu. Beers yesterday afterwards helped. LOL. 

I got this today on my new build.

**Comment by soumith** [comment]
sorry about this. I just fixed the fblualib install script so that this error does not happen now.
I made sure tagged versions of folly and fbthrift are installed, rather than trunk. I tested the install process on a fresh ubuntu 14.04 machine.

You'll have to redo the install process starting from this step:
https://github.com/facebook/fbcunn/blob/master/INSTALL.md#install-folly-fbthrift-thpp-and-fblualib

If you are having installation errors after retrying the install once more (after my fresh fixes), 
I can post the binaries here for Ubuntu 14.04 (they will be specific to ubuntu 14.04).
